### ISSUE TITLE
Unable to install kubernetes csi-rbdplugin (rook-ceph) due to module rbd not found

### ISSUE THREAD

**Issue by jikunchong** [radxa-repo/bsp#48]
board: Rock 5b
system image: [rock-5b_ubuntu_jammy_cli_b38.img.xz](https://github.com/radxa-build/rock-5b/releases/download/b38/rock-5b_ubuntu_jammy_cli_b38.img.xz)
kernel (uname -r): 5.10.110-13-rockchip

step docs: https://kubesphere.cloud/docs/ksv/02-quick-start/01-install-ksv-in-single-node-mode/

```shell
rock@rock-5b:~$ sudo su
./install.sh -a
# ...
kubectl get pod -A
```

```shell
# ...
rook-ceph                          csi-rbdplugin-provisioner-7dfb48857f-bd2dk          6/6     Running             144        17d
rook-ceph                          csi-rbdplugin-x7867                                 2/3     CrashLoopBackOff    12         16m
rook-ceph                          rook-ceph-crashcollector-rock-5b-66c67c6946-nszsd   1/1     Running             20         17d
rook-ceph                          rook-ceph-mgr-a-7cc877f79-7xn66                     1/1     Running             20         17d
rook-ceph                          rook-ceph-mon-a-784bbb98f6-2zh2h                    1/1     Running             21         17d
rook-ceph                          rook-ceph-operator-5fdc669785-4pcns                 1/1     Running             20         17d
rook-ceph                          rook-ceph-osd-0-85447777cc-m5ltn                    1/1     Running             19         17d
rook-ceph                          rook-ceph-osd-prepare-rock-5b-jvl5q                 0/1     Completed           0          10m
rook-ceph                          rook-ceph-tools-6c55fbd449-4c5hj                    1/1     Running             20         17d
rook-ceph                          rook-discover-xhcdr                                 1/1     Running             20         17d
rook-ceph                          snapshot-controller-0                               1/1     Running             20         17d
# ...
```

```shell
kubectl logs csi-rbdplugin-x7867 csi-rbdplugin -n rook-ceph
```

```shell
E0828 07:45:17.577412   16347 cephcsi.go:187] Failed to get the PID limit, can not reconfigure: could not find a cgroup for 'pids'
E0828 07:45:17.717663   16347 rbd_util.go:241] modprobe failed: an error (exit status 1) occurred while running modprobe args: [rbd]
F0828 07:45:17.717721   16347 driver.go:148] an error (exit status 1) occurred while running modprobe args: [rbd]
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1038 +0xac
# ...
```

```shell
modprobe rbd
```

```shell
modprobe: FATAL: Module rbd not found in directory /lib/modules/5.10.110-13-rockchip
```

so, please add CONFIG_BLK_DEV_RBD=m in linux/.common/kconfig.conf L753. thanks.

**Comment by jikunchong** [comment]
If possible, please also enable CONFIG_ CEPH_FS=m

**Comment by RadxaYuntian** [comment]
I'd suggest using ceph-fuse package instead. The kernel driver is old.

**Comment by jikunchong** [comment]
Oh, please ignore CONFIG_ CEPH_ FS option, I haven't configured CephFS yet.
